In [56]:
import numpy as np
import matplotlib.pyplot as plt
import os
DIR = os.getcwd() + "/../data/"

In [213]:
files = os.listdir(DIR + "npy-images")
labels = np.load(DIR + "labels.npy")

In [214]:
files

['10175.npy',
 '538.npy',
 '7609.npy',
 '1868.npy',
 '1072.npy',
 '7117.npy',
 '9313.npy',
 '6472.npy',
 '2063.npy',
 '3098.npy',
 '771.npy',
 '4871.npy',
 '2234.npy',
 '10456.npy',
 '68.npy',
 '3097.npy',
 '9096.npy',
 '5725.npy',
 '3223.npy',
 '891.npy',
 '1662.npy',
 '8622.npy',
 '5397.npy',
 '1094.npy',
 '2213.npy',
 '414.npy',
 '174.npy',
 '6804.npy',
 '1768.npy',
 '9448.npy',
 '8416.npy',
 '5647.npy',
 '842.npy',
 '7421.npy',
 '5279.npy',
 '4333.npy',
 '3053.npy',
 '10502.npy',
 '5220.npy',
 '9366.npy',
 '2641.npy',
 '92.npy',
 '1173.npy',
 '9348.npy',
 '7802.npy',
 '9670.npy',
 '8366.npy',
 '838.npy',
 '6941.npy',
 '9459.npy',
 '7310.npy',
 '7217.npy',
 '7377.npy']

In [215]:
print(len(files))
print(labels.shape)

53
(2000, 3)


In [216]:
ns = 4

In [217]:
data = np.zeros((ns*len(files), 512*512))

In [218]:
cov_labels = labels[:,1]
sev_labels = cov_labels + labels[:,2]
print(cov_labels[0:len(files)])
print(sev_labels[0:len(files)])

[1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1.
 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1.
 0. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 0. 0. 2. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 2. 2. 1. 0. 0. 2.
 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 2. 2. 0. 2. 0. 0. 1. 2. 1. 0. 0. 0. 1. 1.
 0. 2. 2. 2. 1.]


In [219]:
dlabels = np.zeros(ns*len(files))

for i in range(len(files)):
    img = np.load(DIR + "npy-images/" + str(int(labels[i,0])) + ".npy")
    idx = int(img.shape[0]/2)
    data[i*ns,:] = img[idx,:,:].flatten()
    data[i*ns+1,:] = img[idx+1,:,:].flatten()
    data[i*ns-1,:] = img[idx-1,:,:].flatten()
    data[i*ns-2,:] = img[idx-2,:,:].flatten()
    l = int(sev_labels[i])
    dlabels[i*ns] = l
    dlabels[i*ns+1] = l
    dlabels[i*ns-1] = l
    dlabels[i*ns-2] = l

In [202]:
data

array([[-2048., -2048., -2048., ..., -2048., -2048., -2048.],
       [-2048., -2048., -2048., ..., -2048., -2048., -2048.],
       [-1022., -1021., -1019., ..., -1024., -1024., -1024.],
       ...,
       [-1024., -1024., -1024., ..., -1024., -1024., -1024.],
       [-2048., -2048., -2048., ..., -2048., -2048., -2048.],
       [-2048., -2048., -2048., ..., -2048., -2048., -2048.]])

In [220]:
from sklearn.model_selection import train_test_split

X_tmp, X_test, y_tmp, y_test = train_test_split(data, dlabels, test_size=0.2, train_size=0.8, random_state=42, shuffle=True)
X_train, X_val, y_train, y_val = train_test_split(X_tmp, y_tmp, test_size=0.25, train_size=0.75, random_state=42, shuffle=True)

In [186]:
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import BernoulliNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

In [221]:
mod = svm.SVC()
mod.fit(X_train, y_train)
print(mod.score(X_val, y_val))
preds = mod.predict(X_val)
print(confusion_matrix(preds, y_val))
print(mod.score(X_test, y_test))
preds = mod.predict(X_test)
print(confusion_matrix(preds, y_test))

0.7209302325581395
[[13  8  1]
 [ 0 17  3]
 [ 0  0  1]]
0.8372093023255814
[[17  0  2]
 [ 0 15  5]
 [ 0  0  4]]


In [222]:
mod = GaussianNB()
mod.fit(X_train, y_train)
print(mod.score(X_val, y_val))
preds = mod.predict(X_val)
print(confusion_matrix(preds, y_val))
print(mod.score(X_test, y_test))
preds = mod.predict(X_test)
print(confusion_matrix(preds, y_test))

0.5813953488372093
[[ 6  7  0]
 [ 2 16  2]
 [ 5  2  3]]
0.6744186046511628
[[11  1  0]
 [ 3 11  4]
 [ 3  3  7]]


In [223]:
mod = BernoulliNB()
mod.fit(X_train, y_train)
print(mod.score(X_val, y_val))
preds = mod.predict(X_val)
print(confusion_matrix(preds, y_val))
print(mod.score(X_test, y_test))
preds = mod.predict(X_test)
print(confusion_matrix(preds, y_test))

0.8604651162790697
[[13  5  1]
 [ 0 20  0]
 [ 0  0  4]]
0.9069767441860465
[[17  1  2]
 [ 0 14  1]
 [ 0  0  8]]


In [224]:
mod = DecisionTreeClassifier()
mod.fit(X_train, y_train)
print(mod.score(X_val, y_val))
preds = mod.predict(X_val)
print(confusion_matrix(preds, y_val))
print(mod.score(X_test, y_test))
preds = mod.predict(X_test)
print(confusion_matrix(preds, y_test))

0.7209302325581395
[[12  6  1]
 [ 1 15  0]
 [ 0  4  4]]
0.8604651162790697
[[15  1  1]
 [ 1 14  2]
 [ 1  0  8]]


In [225]:
mod = KNeighborsClassifier()
mod.fit(X_train, y_train)
print(mod.score(X_val, y_val))
preds = mod.predict(X_val)
print(confusion_matrix(preds, y_val))
print(mod.score(X_test, y_test))
preds = mod.predict(X_test)
print(confusion_matrix(preds, y_test))

0.5116279069767442
[[ 6 10  0]
 [ 3 12  1]
 [ 4  3  4]]
0.6976744186046512
[[11  2  0]
 [ 2  9  1]
 [ 4  4 10]]


In [211]:
from sklearn.linear_model import LinearRegression

In [226]:
mod = svm.SVR()
mod.fit(X_train, y_train)
print(mod.score(X_val, y_val))
preds = [(2 if p >= 1.5 else 1) if p >= 0.5 else 0 for p in mod.predict(X_val)]
print(confusion_matrix(preds, y_val))
print(mod.score(X_test, y_test))
preds = [(2 if p >= 1.5 else 1) if p >= 0.5 else 0 for p in mod.predict(X_test)]
print(confusion_matrix(preds, y_test))

0.6377222986116342
[[11  4  0]
 [ 2 21  4]
 [ 0  0  1]]
0.8042993192464213
[[16  0  0]
 [ 1 15  4]
 [ 0  0  7]]


In [227]:
mod = LinearRegression()
mod.fit(X_train, y_train)
print(mod.score(X_val, y_val))
preds = [(2 if p >= 1.5 else 1) if p >= 0.5 else 0 for p in mod.predict(X_val)]
print(confusion_matrix(preds, y_val))
print(mod.score(X_test, y_test))
preds = [(2 if p >= 1.5 else 1) if p >= 0.5 else 0 for p in mod.predict(X_test)]
print(confusion_matrix(preds, y_test))

0.7430831839642866
[[13  4  0]
 [ 0 21  0]
 [ 0  0  5]]
0.994553098961824
[[17  0  0]
 [ 0 15  0]
 [ 0  0 11]]
